### ISSUE TITLE
[BUG] Template: Midnight-blue

### ISSUE THREAD

**Issue by Ano24** [dohliam/libreoffice-impress-templates#7] opened 2017-05-08 10:11 UTC
Hi, 
I am using Libreoffice:
Version: 5.1.6.2
Build ID: 1:5.1.6~rc2-0ubuntu1~xenial2
CPU Threads: 4; OS Version: Linux 4.8; UI Render: default; 
Locale: de-DE (en_US.UTF-8); Calc: group

on a Ubuntu 16.04.2 LTS Maschine. The templates do not realy work correctly. e.g. the midnight-blue tempalte does not show me the title page but only the pages which would come after the title page. I have attached two Screenshots to illustrate my problem. 

![screenshot from 2017-05-08 12-06-03](https://cloud.githubusercontent.com/assets/10831346/25799977/9c79b6de-33e7-11e7-8264-1637931c9eaa.png)
![screenshot from 2017-05-08 12-07-26](https://cloud.githubusercontent.com/assets/10831346/25799980/9f2b513a-33e7-11e7-9db9-b1891b44e83c.png)

**Comment by dohliam** [comment] 2017-05-08 17:48
Hi @Ano24, thanks for reporting this issue. Have you tried downloading the latest version of Midnight Blue to see if you still have the same problem?

I am unable to reproduce this issue on libreoffice 5.1.6.2 on ubuntu xenial (see screenshot below). Are there any other templates that don't seem to be working?

![image](https://cloud.githubusercontent.com/assets/9295750/25817247/9c1ac40a-33db-11e7-8823-c949f8ecda71.png)

**Comment by dohliam** [comment] 2019-04-22 19:31
Closing this as Midnight Blue template is working as expected on latest version of LibreOffice.

**Closed by dohliam** 2019-04-22 19:31 UTC
